version: '3.2'
services:
    db:
        image: 'postgres:14.0'
        environment:
            POSTGRES_DB: blog_platform_db
            POSTGRES_PASSWORD: postgres
        ports:
            - '15432:5432'
        restart: always

            
            